<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    <PackageReference Include="Twilio" Version="7.14.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gizmosbuy.Core\Gizmosbuy.Core.csproj" />
    <ProjectReference Include="..\Gizmosbuy.DAL\Gizmosbuy.DAL.csproj" />
  </ItemGroup>

</Project>
