// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class ApprovalStatus
{
    public int ApprovalStatusId { get; set; }

    public string ApprovalStatusName { get; set; }

    public virtual ICollection<StoreReturnItemNotification> StoreReturnItemNotifications { get; set; } = new List<StoreReturnItemNotification>();
}