// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class BrandMaster
{
    public int BrandId { get; set; }

    public string BrandName { get; set; }

    public bool? IsActive { get; set; }
}