// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class DeleteSalesType
    {
        [StringLength(50)]
        public string BillNo { get; set; }
        public int? SalesID { get; set; }
        public int? PurchaseID { get; set; }
        public int? SellingQuantity { get; set; }
    }
}
