// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class Expense
{
    public int ExpenseId { get; set; }

    public DateTime? ExpenseDate { get; set; }

    public decimal? Amount { get; set; }

    public int? ExpenseTypeId { get; set; }

    public string Remark { get; set; }

    public int? PaymentModeId { get; set; }

    public short? ExpenseMonth { get; set; }

    public short? ExpenseYear { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }
}