// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class LocationMaster
{
    public int LocationId { get; set; }

    public string LocationName { get; set; }

    public bool? IsActive { get; set; }

    public string Address { get; set; }

    public long? ContactNo { get; set; }

    public string LocationCode { get; set; }

    public virtual ICollection<UserLocationMapping> UserLocationMappings { get; set; } = new List<UserLocationMapping>();

    public virtual ICollection<UserMaster> UserMasters { get; set; } = new List<UserMaster>();
}