// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class PaymentModeMaster
{
    public int PaymentModeId { get; set; }

    public string PaymentModeName { get; set; }

    public bool? IsActive { get; set; }
}