// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class Purchase
{
    public int PurchaseId { get; set; }

    public string SerialNo { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public int? CategoryId { get; set; }

    public int? BrandId { get; set; }

    public string Model { get; set; }

    public string Specifications { get; set; }

    public decimal? PurchasePrice { get; set; }

    public int? Quantity { get; set; }

    public decimal? UpgradePrice { get; set; }

    public decimal? TotalPrice { get; set; }

    public string PaymentMode { get; set; }

    public string BuyingLead { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ICollection<Sale> Sales { get; set; } = new List<Sale>();

    public virtual ICollection<TempSale> TempSales { get; set; } = new List<TempSale>();
}