// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class SalesJournal
{
    public int SalesJournal1 { get; set; }

    public int SalesId { get; set; }

    public int? PurchaseQuantity { get; set; }

    public int? SellingQuantity { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Sale Sales { get; set; }
}