// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetExpenseSummaryDataResult
    {
        [StringLength(50)]
        public string ExpenseType { get; set; }
        [Column("SumAmount", TypeName = "money")]
        public decimal SumAmount { get; set; }
        public long? OrderBy { get; set; }
    }
}
