// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetValidateLoginResult
    {
        public int UserID { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(20)]
        public string UserRole { get; set; }
        public int? LocationID { get; set; }
        [StringLength(100)]
        public string Location { get; set; }
    }
}
