// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetExpenseListResult
    {
        public int ExpenseID { get; set; }
        public DateTime? ExpenseDate { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(50)]
        public string ExpenseTypeName { get; set; }
        [StringLength(500)]
        public string Remark { get; set; }
        [StringLength(50)]
        public string PaymentModeName { get; set; }
        public short? ExpenseMonth { get; set; }
        [StringLength(30)]
        public string ExpenseMonthName { get; set; }
        public short? ExpenseYear { get; set; }
        [StringLength(100)]
        public string LocationName { get; set; }
    }
}
