// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetPurchaseListResult
    {
        public int PurchaseID { get; set; }
        [StringLength(100)]
        public string SerialNo { get; set; }
        public DateTime? PurchaseDate { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }
        [StringLength(100)]
        public string BrandName { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(1000)]
        public string Specifications { get; set; }
        [Column("PurchasePrice", TypeName = "money")]
        public decimal? PurchasePrice { get; set; }
        public int? Quantity { get; set; }
        [Column("UpgradePrice", TypeName = "money")]
        public decimal? UpgradePrice { get; set; }
        [Column("TotalPrice", TypeName = "money")]
        public decimal? TotalPrice { get; set; }
        [StringLength(100)]
        public string PaymentMode { get; set; }
        [StringLength(100)]
        public string BuyingLead { get; set; }
        public int? CanDelete { get; set; }
    }
}
