// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetStoreTransferInvoiceDetailsResult
    {
        public int StoreTransferID { get; set; }
        [StringLength(50)]
        public string BillNo { get; set; }
        [StringLength(100)]
        public string SerialNo { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(100)]
        public string BrandName { get; set; }
        [StringLength(1000)]
        public string Specifications { get; set; }
        public int? FromLocationID { get; set; }
        public int? ToLocationID { get; set; }
        public int? SellingQuantity { get; set; }
        public int? TransferPurchaseID { get; set; }
    }
}
