// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetTransferPaymentNotificationsListResult
    {
        public int TransferPaymentID { get; set; }
        public DateTime? PaymentDate { get; set; }
        [Column("Amount", TypeName = "money")]
        public decimal? Amount { get; set; }
        [StringLength(50)]
        public string TransferMode { get; set; }
        [StringLength(200)]
        public string Remark { get; set; }
        [StringLength(100)]
        public string FromLocation { get; set; }
        public bool? IsApproved { get; set; }
    }
}
