// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetStoreTransferRawDataResult
    {
        public int StoreTransferID { get; set; }
        public int PurchaseID { get; set; }
        [StringLength(100)]
        public string SerialNo { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }
        [StringLength(100)]
        public string BrandName { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(1000)]
        public string Specifications { get; set; }
        public DateTime? TransferDate { get; set; }
        [Column("SellingPrice", TypeName = "money")]
        public decimal? SellingPrice { get; set; }
        public int? SellingQuantity { get; set; }
        [Column("TotalPrice", TypeName = "money")]
        public decimal? TotalPrice { get; set; }
        [StringLength(100)]
        public string FromLocation { get; set; }
        [StringLength(100)]
        public string ToLocation { get; set; }
    }
}
