// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetSalesReportHeaderResult
    {
        [StringLength(100)]
        public string CustomerName { get; set; }
        public long? ContactNo { get; set; }
        [StringLength(100)]
        public string Location { get; set; }
        [StringLength(50)]
        public string InvoiceNo { get; set; }
        public DateTime? SellingDate { get; set; }
        [StringLength(100)]
        public string PaymentModeName { get; set; }
        [StringLength(100)]
        public string SellingLead { get; set; }
    }
}
