// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetPurchaseSummaryDataResult
    {
        [StringLength(100)]
        public string CategoryName { get; set; }
        public int Quantity { get; set; }
        [Column("PurchaseAmount", TypeName = "money")]
        public decimal PurchaseAmount { get; set; }
        public long? OrderBy { get; set; }
    }
}
