// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetRawDataResult
    {
        public long? SrNo { get; set; }
        [StringLength(100)]
        public string SerialNo { get; set; }
        public DateTime? PurchaseDate { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }
        [StringLength(100)]
        public string BrandName { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(1000)]
        public string Specifications { get; set; }
        [Column("PurchasePrice", TypeName = "money")]
        public decimal? PurchasePrice { get; set; }
        public int? PurchaseQuantity { get; set; }
        [Column("UpgradePrice", TypeName = "money")]
        public decimal? UpgradePrice { get; set; }
        [Column("TotalPrice", TypeName = "money")]
        public decimal? TotalPrice { get; set; }
        [StringLength(100)]
        public string PurchasePaymentMode { get; set; }
        [StringLength(100)]
        public string BuyingLead { get; set; }
        [StringLength(7)]
        public string StockStatus { get; set; }
        public DateTime? SellingDate { get; set; }
        [Column("SellingPrice", TypeName = "money")]
        public decimal? SellingPrice { get; set; }
        public int? SellingQuantity { get; set; }
        [Column("Profit", TypeName = "money")]
        public decimal? Profit { get; set; }
        [Column("Loss", TypeName = "money")]
        public decimal? Loss { get; set; }
        public int? RemainingQuantity { get; set; }
        [StringLength(100)]
        public string SalesPaymentMode { get; set; }
        [StringLength(100)]
        public string SellingLead { get; set; }
        [StringLength(100)]
        public string CustomerName { get; set; }
        public long? ContactNo { get; set; }
        [StringLength(100)]
        public string Location { get; set; }
        [StringLength(50)]
        public string BillNo { get; set; }
        [StringLength(3)]
        public string SellMonth { get; set; }
        public int? SellYear { get; set; }
        [StringLength(100)]
        public string StoreName { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}
