// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetTempStoreTransferByIDResult
    {
        public int TempStoreTransferID { get; set; }
        [StringLength(100)]
        public string SerialNo { get; set; }
        public int? CategoryID { get; set; }
        [StringLength(100)]
        public string CategoryName { get; set; }
        public int? BrandID { get; set; }
        [StringLength(100)]
        public string BrandName { get; set; }
        [StringLength(50)]
        public string Model { get; set; }
        [StringLength(1000)]
        public string Specifications { get; set; }
        public int? Quantity { get; set; }
        public int? SellingQuantity { get; set; }
        public DateTime? TransferDate { get; set; }
        [Column("SellingPrice", TypeName = "money")]
        public decimal? SellingPrice { get; set; }
        public int? ToLocationID { get; set; }
        [StringLength(100)]
        public string ToLocationName { get; set; }
        [StringLength(50)]
        public string BillNo { get; set; }
        public int PurchaseID { get; set; }
    }
}
