// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Gizmosbuy.DAL.Models
{
    public partial class spGetSerialNoListResult
    {
        public int PurchaseId { get; set; }
        [StringLength(1208)]
        public string Description { get; set; }
    }
}
