// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class StoreReturnItemNotification
{
    public int StoreReturnItemNotificationId { get; set; }

    public string BillNo { get; set; }

    public int? FromLocationId { get; set; }

    public int? ToLocationId { get; set; }

    public int? ReturnQuantity { get; set; }

    public int? TransferPurchaseId { get; set; }

    public int? ApprovalStatusId { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual ApprovalStatus ApprovalStatus { get; set; }
}