// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class StoreTransfer
{
    public int StoreTransferId { get; set; }

    public int PurchaseId { get; set; }

    public DateTime? TransferDate { get; set; }

    public decimal? SellingPrice { get; set; }

    public int? SellingQuantity { get; set; }

    public int? FromLocationId { get; set; }

    public int? ToLocationId { get; set; }

    public string BillNo { get; set; }

    public bool IsReturned { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? TransferPurchaseId { get; set; }

    public virtual Purchase Purchase { get; set; }
}