// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class TempSale
{
    public int TempSalesId { get; set; }

    public int PurchaseId { get; set; }

    public DateTime? SellingDate { get; set; }

    public decimal? SellingPrice { get; set; }

    public int? SellingQuantity { get; set; }

    public string PaymentMode { get; set; }

    public string SellingLead { get; set; }

    public string CustomerName { get; set; }

    public long? ContactNo { get; set; }

    public string Location { get; set; }

    public string BillNo { get; set; }

    public string Warranty { get; set; }

    public string Remark { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? UserId { get; set; }

    public virtual Purchase Purchase { get; set; }
}