// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gizmosbuy.DAL.Models;

public partial class UserLocationMapping
{
    public int UserLocationMappingId { get; set; }

    public int? UserId { get; set; }

    public int? LocationId { get; set; }

    public virtual LocationMaster Location { get; set; }

    public virtual UserMaster User { get; set; }
}