// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Gizmosbuy.DAL.Models;
using Microsoft.EntityFrameworkCore;

namespace Gizmosbuy.DAL.Data;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ApprovalStatus> ApprovalStatuses { get; set; }

    public virtual DbSet<BrandMaster> BrandMasters { get; set; }

    public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }

    public virtual DbSet<Expense> Expenses { get; set; }

    public virtual DbSet<ExpenseTypeMaster> ExpenseTypeMasters { get; set; }

    public virtual DbSet<LocationMaster> LocationMasters { get; set; }

    public virtual DbSet<PaymentModeMaster> PaymentModeMasters { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<Sale> Sales { get; set; }

    public virtual DbSet<SalesDeleted> SalesDeleteds { get; set; }

    public virtual DbSet<SalesJournal> SalesJournals { get; set; }

    public virtual DbSet<SalesJournalDeleted> SalesJournalDeleteds { get; set; }

    public virtual DbSet<StoreReturnItemNotification> StoreReturnItemNotifications { get; set; }

    public virtual DbSet<StoreTransfer> StoreTransfers { get; set; }

    public virtual DbSet<TempSale> TempSales { get; set; }

    public virtual DbSet<TempStoreTransfer> TempStoreTransfers { get; set; }

    public virtual DbSet<TransferPayment> TransferPayments { get; set; }

    public virtual DbSet<UserLocationMapping> UserLocationMappings { get; set; }

    public virtual DbSet<UserMaster> UserMasters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ApprovalStatus>(entity =>
        {
            entity.HasKey(e => e.ApprovalStatusId).HasName("PK__Approval__08E52618BFB6C76F");

            entity.ToTable("ApprovalStatus");

            entity.Property(e => e.ApprovalStatusId)
                .ValueGeneratedNever()
                .HasColumnName("ApprovalStatusID");
            entity.Property(e => e.ApprovalStatusName)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BrandMaster>(entity =>
        {
            entity.HasKey(e => e.BrandId).HasName("PK__Brands__DAD4F3BEF9920761");

            entity.ToTable("BrandMaster");

            entity.Property(e => e.BrandId).HasColumnName("BrandID");
            entity.Property(e => e.BrandName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(false);
        });

        modelBuilder.Entity<CategoryMaster>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A2B0B896D14");

            entity.ToTable("CategoryMaster");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(false);
        });

        modelBuilder.Entity<Expense>(entity =>
        {
            entity.HasKey(e => e.ExpenseId).HasName("PK__Expenses__1445CFF3B639300E");

            entity.Property(e => e.ExpenseId).HasColumnName("ExpenseID");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ExpenseDate).HasColumnType("datetime");
            entity.Property(e => e.ExpenseTypeId).HasColumnName("ExpenseTypeID");
            entity.Property(e => e.LocationId).HasColumnName("LocationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentModeId).HasColumnName("PaymentModeID");
            entity.Property(e => e.Remark)
                .HasMaxLength(500)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ExpenseTypeMaster>(entity =>
        {
            entity.HasKey(e => e.ExpenseTypeId).HasName("PK__ExpenseT__E082A36F63B89EDF");

            entity.ToTable("ExpenseTypeMaster");

            entity.Property(e => e.ExpenseTypeId).HasColumnName("ExpenseTypeID");
            entity.Property(e => e.ExpenseTypeName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(false);
        });

        modelBuilder.Entity<LocationMaster>(entity =>
        {
            entity.HasKey(e => e.LocationId).HasName("PK__Location__E7FEA47731190052");

            entity.ToTable("LocationMaster");

            entity.Property(e => e.LocationId).HasColumnName("LocationID");
            entity.Property(e => e.Address)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.IsActive).HasDefaultValue(false);
            entity.Property(e => e.LocationCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.LocationName)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PaymentModeMaster>(entity =>
        {
            entity.HasKey(e => e.PaymentModeId).HasName("PK__PaymentM__F9599529B52ED2C4");

            entity.ToTable("PaymentModeMaster");

            entity.Property(e => e.PaymentModeId).HasColumnName("PaymentModeID");
            entity.Property(e => e.IsActive).HasDefaultValue(false);
            entity.Property(e => e.PaymentModeName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.PurchaseId).HasName("PK__Purchase__6B0A6BDEA237620C");

            entity.Property(e => e.PurchaseId).HasColumnName("PurchaseID");
            entity.Property(e => e.BrandId).HasColumnName("BrandID");
            entity.Property(e => e.BuyingLead)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Model)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentMode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PurchaseDate).HasColumnType("datetime");
            entity.Property(e => e.PurchaseLocationId).HasColumnName("PurchaseLocationID");
            entity.Property(e => e.PurchasePrice).HasColumnType("money");
            entity.Property(e => e.SerialNo)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Specifications)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.TotalPrice).HasColumnType("money");
            entity.Property(e => e.UpgradePrice).HasColumnType("money");
        });

        modelBuilder.Entity<Sale>(entity =>
        {
            entity.HasKey(e => e.SalesId).HasName("PK__Sales__C952FB12FCB88CDF");

            entity.Property(e => e.SalesId).HasColumnName("SalesID");
            entity.Property(e => e.BillNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Location)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentMode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PurchaseId).HasColumnName("PurchaseID");
            entity.Property(e => e.Remark)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.SellingDate).HasColumnType("datetime");
            entity.Property(e => e.SellingLead)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SellingPrice).HasColumnType("money");
            entity.Property(e => e.Warranty)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Purchase).WithMany(p => p.Sales)
                .HasForeignKey(d => d.PurchaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Sales__PurchaseI__625A9A57");
        });

        modelBuilder.Entity<SalesDeleted>(entity =>
        {
            entity.HasKey(e => e.SalesId).HasName("PK__Sales_De__C952FB120906A4E2");

            entity.ToTable("Sales_Deleted");

            entity.Property(e => e.SalesId).HasColumnName("SalesID");
            entity.Property(e => e.BillNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Location)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PaymentMode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PurchaseId).HasColumnName("PurchaseID");
            entity.Property(e => e.Remark)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.SellingDate).HasColumnType("datetime");
            entity.Property(e => e.SellingLead)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SellingPrice).HasColumnType("money");
            entity.Property(e => e.Warranty)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SalesJournal>(entity =>
        {
            entity.HasKey(e => e.SalesJournalId).HasName("PK__SalesJou__4F0AA0A12BFE71EB");

            entity.ToTable("SalesJournal");

            entity.Property(e => e.SalesJournalId).HasColumnName("SalesJournalID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.SalesId).HasColumnName("SalesID");

            entity.HasOne(d => d.Sales).WithMany(p => p.SalesJournals)
                .HasForeignKey(d => d.SalesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesJour__Sales__662B2B3B");
        });

        modelBuilder.Entity<SalesJournalDeleted>(entity =>
        {
            entity.HasKey(e => e.SalesJournalId).HasName("PK__SalesJou__295F7548F0519562");

            entity.ToTable("SalesJournal_Deleted");

            entity.Property(e => e.SalesJournalId).HasColumnName("SalesJournalID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.SalesId).HasColumnName("SalesID");

            entity.HasOne(d => d.Sales).WithMany(p => p.SalesJournalDeleteds)
                .HasForeignKey(d => d.SalesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SalesJour__Sales__15702A09");
        });

        modelBuilder.Entity<StoreReturnItemNotification>(entity =>
        {
            entity.HasKey(e => e.StoreReturnItemNotificationId).HasName("PK__StoreRet__12C6C6B008B4185F");

            entity.ToTable("StoreReturnItemNotification");

            entity.Property(e => e.StoreReturnItemNotificationId).HasColumnName("StoreReturnItemNotificationID");
            entity.Property(e => e.ApprovalStatusId).HasColumnName("ApprovalStatusID");
            entity.Property(e => e.BillNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FromLocationId).HasColumnName("FromLocationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.ToLocationId).HasColumnName("ToLocationID");
            entity.Property(e => e.TransferPurchaseId).HasColumnName("TransferPurchaseID");

            entity.HasOne(d => d.ApprovalStatus).WithMany(p => p.StoreReturnItemNotifications)
                .HasForeignKey(d => d.ApprovalStatusId)
                .HasConstraintName("FK_RetrunTransferApproval_ApprovalStatusID");
        });

        modelBuilder.Entity<StoreTransfer>(entity =>
        {
            entity.HasKey(e => e.StoreTransferId).HasName("PK__StoreTra__70452446291E27A2");

            entity.ToTable("StoreTransfer");

            entity.Property(e => e.StoreTransferId).HasColumnName("StoreTransferID");
            entity.Property(e => e.BillNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FromLocationId).HasColumnName("FromLocationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PurchaseId).HasColumnName("PurchaseID");
            entity.Property(e => e.SellingPrice).HasColumnType("money");
            entity.Property(e => e.ToLocationId).HasColumnName("ToLocationID");
            entity.Property(e => e.TransferDate).HasColumnType("datetime");
            entity.Property(e => e.TransferPurchaseId).HasColumnName("TransferPurchaseID");

            entity.HasOne(d => d.Purchase).WithMany(p => p.StoreTransfers)
                .HasForeignKey(d => d.PurchaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_StoreTransfer_Purchase");
        });

        modelBuilder.Entity<TempSale>(entity =>
        {
            entity.HasKey(e => e.TempSalesId).HasName("PK__TempSale__C508D4FF4D71675C");

            entity.Property(e => e.TempSalesId).HasColumnName("TempSalesID");
            entity.Property(e => e.BillNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CustomerName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Location)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentMode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PurchaseId).HasColumnName("PurchaseID");
            entity.Property(e => e.Remark)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SellingDate).HasColumnType("datetime");
            entity.Property(e => e.SellingLead)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SellingPrice).HasColumnType("money");
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Warranty)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Purchase).WithMany(p => p.TempSales)
                .HasForeignKey(d => d.PurchaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TempSales__Purch__11007AA7");
        });

        modelBuilder.Entity<TempStoreTransfer>(entity =>
        {
            entity.HasKey(e => e.TempStoreTransferId).HasName("PK__TempStor__881056733EFB2992");

            entity.ToTable("TempStoreTransfer");

            entity.Property(e => e.TempStoreTransferId).HasColumnName("TempStoreTransferID");
            entity.Property(e => e.BillNo)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FromLocationId).HasColumnName("FromLocationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PurchaseId).HasColumnName("PurchaseID");
            entity.Property(e => e.SellingPrice).HasColumnType("money");
            entity.Property(e => e.ToLocationId).HasColumnName("ToLocationID");
            entity.Property(e => e.TransferDate).HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Purchase).WithMany(p => p.TempStoreTransfers)
                .HasForeignKey(d => d.PurchaseId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TempStoreTransfer_Purchase");
        });

        modelBuilder.Entity<TransferPayment>(entity =>
        {
            entity.HasKey(e => e.TransferPaymentId).HasName("PK__Transfer__3923068B6B1C2081");

            entity.ToTable("TransferPayment");

            entity.Property(e => e.TransferPaymentId).HasColumnName("TransferPaymentID");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FromLocationId).HasColumnName("FromLocationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentDate).HasColumnType("datetime");
            entity.Property(e => e.Remark)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.ToLocationId).HasColumnName("ToLocationID");
            entity.Property(e => e.TransferMode)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserLocationMapping>(entity =>
        {
            entity.HasKey(e => e.UserLocationMappingId).HasName("PK__UserLoca__DA68405D35755DCA");

            entity.ToTable("UserLocationMapping");

            entity.Property(e => e.UserLocationMappingId).HasColumnName("UserLocationMappingID");
            entity.Property(e => e.LocationId).HasColumnName("LocationID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Location).WithMany(p => p.UserLocationMappings)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("UserLocationMapping_LocationID_FK");

            entity.HasOne(d => d.User).WithMany(p => p.UserLocationMappings)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("UserLocationMapping_UserID_FK");
        });

        modelBuilder.Entity<UserMaster>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC7980290B");

            entity.ToTable("UserMaster");

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FirstName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LocationId).HasColumnName("LocationID");
            entity.Property(e => e.Password)
                .HasMaxLength(100)
                .IsUnicode(false)
                .UseCollation("SQL_Latin1_General_CP1_CS_AS");
            entity.Property(e => e.UserName)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.UserRole)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Location).WithMany(p => p.UserMasters)
                .HasForeignKey(d => d.LocationId)
                .HasConstraintName("FK_LocationMaster_LocationID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}