// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Gizmosbuy.DAL.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Gizmosbuy.DAL.Data
{
    public partial interface IApplicationDbContextProcedures
    {
        Task<List<spGetPurchaseByIDResult>> spGetPurchaseByIDAsync(int? purchaseID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPurchaseListResult>> spGetPurchaseListAsync(int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPurchaseSummaryDataResult>> spGetPurchaseSummaryDataAsync(int? locationId, int? month, int? year, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetRawDataResult>> spGetRawDataAsync(string startDate, string endDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesByIDResult>> spGetSalesByIDAsync(int? salesID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesListResult>> spGetSalesListAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesReportDataResult>> spGetSalesReportDataAsync(string invoiceNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesReportHeaderResult>> spGetSalesReportHeaderAsync(string invoiceNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesSummaryDataResult>> spGetSalesSummaryDataAsync(int? locationId, int? month, int? year, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTempSalesByIDResult>> spGetTempSalesByIDAsync(int? tempSalesID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTempSalesListResult>> spGetTempSalesListAsync(int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetValidateLoginResult>> spGetValidateLoginAsync(string userName, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spSaveSalesAsync(int? salesID, int? purchaseID, DateTime? sellingDate, decimal? sellingPrice, int? sellingQuantity, int? paymentModeID, string sellingLead, string customerName, long? contactNo, string location, string billNo, int? createdBy, DateTime? createdDate, int? modifiedBy, DateTime? modifiedDate, string actionType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
