// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Gizmosbuy.DAL.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace Gizmosbuy.DAL.Data
{
    public partial interface IApplicationDbContextProcedures
    {
        Task<int> spDeleteSalesByInvoiceAsync(string invoiceNo, IEnumerable<DeleteSalesType> deleteSalesList, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDeleteStoreTransferByPurchaseIdAsync(string invoiceNo, int? purchaseId, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetExpenseSummaryDataResult>> spGetExpenseSummaryDataAsync(int? locationId, int? month, int? year, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetInvoiceDetailsResult>> spGetInvoiceDetailsAsync(string invoiceNo, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetLastSalesBillNoResult>> spGetLastSalesBillNoAsync(string billPrefix, string salesType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPurchaseByIDResult>> spGetPurchaseByIDAsync(int? purchaseID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPurchaseListResult>> spGetPurchaseListAsync(int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPurchaseSummaryDataResult>> spGetPurchaseSummaryDataAsync(int? locationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetRawDataResult>> spGetRawDataAsync(string startDate, string endDate, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesByIDResult>> spGetSalesByIDAsync(int? salesID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesListResult>> spGetSalesListAsync(int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesReportDataResult>> spGetSalesReportDataAsync(string invoiceNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesReportHeaderResult>> spGetSalesReportHeaderAsync(string invoiceNo, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSalesSummaryDataResult>> spGetSalesSummaryDataAsync(int? locationId, string salesType, int? date, int? month, int? year, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetSerialNoListResult>> spGetSerialNoListAsync(string searchValue, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetStoreTransferInvoiceDetailsResult>> spGetStoreTransferInvoiceDetailsAsync(string invoiceNo, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetStoreTransferListResult>> spGetStoreTransferListAsync(int? createdBy, int? toLocationID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetStoreTransferNotificationListResult>> spGetStoreTransferNotificationListAsync(int? locationId, int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetStoreTransferPaymentSummaryResult>> spGetStoreTransferPaymentSummaryAsync(int? locationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetStoreTransferRawDataResult>> spGetStoreTransferRawDataAsync(int? locationId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTempSalesByIDResult>> spGetTempSalesByIDAsync(int? tempSalesID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTempSalesListResult>> spGetTempSalesListAsync(int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTempStoreTransferByIDResult>> spGetTempStoreTransferByIDAsync(int? tempStoreTransferID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTempStoreTransferListResult>> spGetTempStoreTransferListAsync(int? userId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTransferPaymentListResult>> spGetTransferPaymentListAsync(int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetTransferPaymentNotificationsListResult>> spGetTransferPaymentNotificationsListAsync(int? createdBy, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetValidateLoginResult>> spGetValidateLoginAsync(string userName, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertSalesDeletedAsync(string invoiceNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spInsertTransferSalesDeletedAsync(int? sales, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spSavePurchaseAsync(int? purchaseID, string serialNo, IEnumerable<SerialNoListType> serialList, DateTime? purchaseDate, int? categoryID, int? brandID, string model, string specifications, decimal? purchasePrice, int? quantity, decimal? upgradePrice, decimal? totalPrice, string paymentMode, string buyingLead, int? purchaseLocationID, int? transactionBy, DateTime? transactionDate, string purchaseType, OutputParameter<int?> result, OutputParameter<int?> idenityValue, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spSaveSalesAsync(int? salesID, int? purchaseID, DateTime? sellingDate, decimal? sellingPrice, int? sellingQuantity, string paymentMode, string sellingLead, string customerName, long? contactNo, string location, string billNo, string warranty, string remark, int? createdBy, DateTime? createdDate, int? modifiedBy, DateTime? modifiedDate, string actionType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spSaveStoreTransferAsync(int? storeTransferID, int? purchaseID, DateTime? transferDate, decimal? sellingPrice, int? sellingQuantity, int? fromLocationID, int? toLocationId, string billNo, int? transferPurchaseID, int? createdBy, DateTime? createdDate, int? modifiedBy, DateTime? modifiedDate, string actionType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spSaveTempSalesAsync(int? tempSalesId, int? purchaseID, DateTime? sellingDate, decimal? sellingPrice, int? purchaseQuantity, int? sellingQuantity, string paymentMode, string sellingLead, string customerName, long? contactNo, string location, string billNo, string warranty, string remark, int? createdBy, DateTime? createdDate, int? modifiedBy, DateTime? modifiedDate, string actionType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spSaveTempStoreTransferAsync(int? tempStoreTransferID, int? purchaseID, DateTime? transferDate, decimal? sellingPrice, int? purchaseQuantity, int? sellingQuantity, int? fromLocationID, int? toLocationID, string billNo, int? createdBy, DateTime? createdDate, int? modifiedBy, DateTime? modifiedDate, string actionType, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
