<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	</PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
	  <None Include="efpt.config.json.user" />
	</ItemGroup>

	<ItemGroup>				
		<PackageReference Include="ClosedXML" Version="0.105.0" />				
		<PackageReference Include="FastReport.Data.MsSql" Version="2026.2.3" />				
		<PackageReference Include="FastReport.OpenSource" Version="2026.2.3" />				
		<PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2026.2.3" />				
		<PackageReference Include="FastReport.OpenSource.Web" Version="2026.2.3" />				
		<PackageReference Include="log4net" Version="3.3.2" />				
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="10.0.10" />				
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />				
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Twilio" Version="7.14.9" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Gizmosbuy.BAL\Gizmosbuy.BAL.csproj" />
	  <ProjectReference Include="..\Gizmosbuy.Core\Gizmosbuy.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="Views\Inventory\_PurchaseSummaryPartial.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Update="Views\Purchase\_PartialPurchaseDeletePopup.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Update="Views\Sales\_PartialDeleteSalesConfirmModal.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Update="Views\Sales\_PartialRefundSoldItems.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
    <Folder Include="wwwroot\TempFiles\" />
	</ItemGroup>

  <ItemGroup>
    <Content Include="Reports\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
